web/views.py
from flask import Blueprint, request, render_template, redirect, url_for,session
from werkzeug.security import check_password_hash

from back.models import Article, User
from utils.webfunctions import is_login

web_blueprint = Blueprint('web',__name__)


@web_blueprint.route('/exitlogin/',methods=['GET'])
@is_login
def exitlogin():
    return redirect(url_for('first.login'))


@web_blueprint.route('/login/',methods=["POST","GET"])
def login():
    if request.method == "GET":
        return render_template('web/login.html')
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        if username and password:
            user = User.query.filter(User.username == username).first()
            if not user:
                error = '该账号不存在，请去注册'
                return render_template('web/login.html',error=error)
            if not check_password_hash(user.password,password):
                error = '密码错误'
                return render_template('web/login.html',error=error)
            session['user_id'] = user.id
            return redirect(url_for('web.web_index'))
        else:
            error = '请填写完整的登录信息'
            return render_template('web/login.html', error=error)


@web_blueprint.route('/index/',methods=['GET'])
@is_login
def web_index():
    if request.method == 'GET':
        articles = Article.query.limit(14).all()
        return render_template('web/index.html',articles=articles)


@web_blueprint.route('/info/<int:id>/',methods=['GET'])
@is_login
def web_info(id):
    if request.method == 'GET':
        article = Article.query.get(id)
        return render_template('web/info.html',article=article)


@web_blueprint.route('/about/', methods=['GET'])
@is_login
def web_about():
    if request.method == 'GET':
        return render_template('web/about.html')


@web_blueprint.route('/list/', methods=['GET'])
@is_login
def list():
    if request.method == 'GET':
        articles = Article.query.limit(5).all()
        return render_template('web/list.html',articles=articles)

templates/web/about.html
{% extends 'web/base.html' %}
{% block gbk %}
    <meta charset="GBK">
{% endblock %}

{% block ul %}
<ul id="starlist">
      <li><a href="/web/index/" >网站首页</a></li>
      <!--<li><a href="share.html">我的相册</a></li>-->
      <li><a href="/web/list/">我的文章</a></li>
      <li ><a href="/web/about/" id="selected">关于我</a></li>
          <li><a href="/web/login/">退出登录</a></li>

      <!--<li><a href="gbook.html">留言</a></li>-->
      <!--<li><a href="/web/info/">内容页</a></li>-->
      <!--<li><a href="infopic.html">内容页</a></li>-->
    </ul>
{% endblock %}
{% block class %}
<article>
  <aside class="l_box">
    <div class="about_me">
      <h2 >关于我</h2>
      <ul>
        <i><img src="/static/web/images/4.jpg"></i>
        <p><b>杨青</b>，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。</p>
      </ul>
    </div>
    <!--<div class="wdxc">-->
      <!--<h2>我的相册</h2>-->
      <!--<ul>-->
        <!--<li><a href="/"><img src="images/7.jpg"></a></li>-->
        <!--<li><a href="/"><img src="images/8.jpg"></a></li>-->
        <!--<li><a href="/"><img src="images/9.jpg"></a></li>-->
        <!--<li><a href="/"><img src="images/10.jpg"></a></li>-->
        <!--<li><a href="/"><img src="images/11.jpg"></a></li>-->
        <!--<li><a href="/"><img src="images/12.jpg"></a></li>-->
      <!--</ul>-->
    <!--</div>-->
    <div class="search">
      <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" type="submit">
      </form>
    </div>
    <div class="fenlei">
      <h2>文章分类</h2>
      <ul>
        <li><a href="/">学无止境</a></li>
        <li><a href="/">日记</a></li>
        <li><a href="/">慢生活</a></li>
        <li><a href="/">美文欣赏</a></li>
      </ul>
    </div>
   
    <div class="guanzhu">
      <h2>关注我 么么哒</h2>
      <ul>
        <img src="/static/web/images/wx.jpg">
      </ul>
    </div>
  </aside>
  <main class="r_box">
     <div class="about">
      <p>昊天，男，一个90后草根男站长！10年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。我入行早，大家也亲切的叫我&ldquo;青姐&rdquo;。<br />
           <br />
            SEO奋斗了将近两年时间，个人博客网站百度排名也从之前的30页后，排到了第一页。期间有很多的不容易，但是都没有放弃过。入了这一行，就深深的喜欢上它。我喜欢一句话&ldquo;冥冥中该来则来，无处可逃&rdquo;。<br />
            <br />
            近几年我也发现个人博客排前几页的也有很多是我做过的模板，感谢各位站长的欣赏，我仔细看过他们的网站。他们在我原模板的基础上有修改，而且他们做的原创内容都是值得一读的。有时候甚至排名都超过了我个人博客网站的排名。<br />
            <br />
            现在很多人向我请教如何做好SEO，我想说的是，一是&ldquo;代码&rdquo;，一定要简单，布局要合理。二是&ldquo;内容&rdquo;，一定要有原创，伪原创也是可以的。三是&ldquo;持续&rdquo;，这是一个持续性过程，一定要有耐心，SEO不是马上生效的。<br />
            <br />
            自从入了这一行，也交到了不少朋友，QQ群也不断的壮大起来，906846621(交流群 <span style="color:#FF0000;">已满员</span>)&nbsp; 280998843（技术群），群里的小伙伴们也很积极的帮助新朋友解决问题，如果你想加入我们，这个大家庭的门，永远给你敞开！另外微信群已于2018.4.13日开通（已满100，只接受群主邀请，可加我个人微信进群 。我的个人微信号 yangqq_1987）</p>
          <br />
           <br />
            SEO奋斗了将近两年时间，个人博客网站百度排名也从之前的30页后，排到了第一页。期间有很多的不容易，但是都没有放弃过。入了这一行，就深深的喜欢上它。我喜欢一句话&ldquo;冥冥中该来则来，无处可逃&rdquo;。<br />
            <br />
           近几年我也发现个人博客排前几页的也有很多是我做过的模板，感谢各位站长的欣赏，我仔细看过他们的网站。他们在我原模板的基础上有修改，而且他们做的原创内容都是值得一读的。有时候甚至排名都超过了我个人博客网站的排名。<br />
            <br />
            现在很多人向我请教如何做好SEO，我想说的是，一是&ldquo;代码&rdquo;，一定要简单，布局要合理。二是&ldquo;内容&rdquo;，一定要有原创，伪原创也是可以的。三是&ldquo;持续&rdquo;，这是一个持续性过程，一定要有耐心，SEO不是马上生效的。<br />
            <br />
            自从入了这一行，也交到了不少朋友，QQ群也不断的壮大起来，280998807(交流群 <span style="color:#FF0000;">已满员</span>)&nbsp; 280998843（技术群），群里的小伙伴们也很积极的帮助新朋友解决问题，如果你想加入我们，这个大家庭的门，永远给你敞开！另外微信群已于2018.4.13日开通（已满100，只接受群主邀请，可加我个人微信进群 。我的个人微信号 yangqq_1987）</p>
          <br />
          <h2>About my blog</h2>
          &nbsp;
          <p>域 名：www.yangqq.com 创建于2011年01月12日&nbsp;</p>
          <br />
          <!--<p>服务器：阿里云服务器&nbsp;&nbsp;<a href="https://promotion.aliyun.com/ntms/act/ambassador/sharetouser.html?userCode=8smrzoqa&amp;productCode=vm" target="_blank"><span style="color:#FF0000;"><strong>前往阿里云官网购买&gt;&gt;</strong></span></a></p>-->
          <br />
          <p>备案号：蜀ICP备11002373号-1</p>
          <br />
          <p>程 序：PHP 帝国CMS7.5</p>
  
     </div>
  </main>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
{% endblock %}

templates/web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block gbk %}
    <meta charset="utf-8">
    {% endblock %}
    <title>首页_昊天 - 一个站在web前端设计之路的技术员个人博客网站</title>
<meta name="keywords" content="个人博客,昊天个人博客,个人博客模板,昊天" />
<meta name="description" content="昊天个人博客，是一个站在web前端设计之路的程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="/static/web/css/base.css" rel="stylesheet">
<link href="/static/web/css/index.css" rel="stylesheet">
<link href="/static/web/css/m.css" rel="stylesheet">
<script src="/static/web/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/web/js/hc-sticky.js"></script>
<script type="text/javascript" src="/static/web/js/comm.js"></script>
<!--[if lt IE 9]>
<script src="/static/web/js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">昊天个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
   {% block ul %}
      {% endblock %}
</nav>
</header>

      {% block class %}
      {% endblock %}

<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">昊天个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>
</html>

templates/web/index.html
{% extends 'web/base.html' %}

{% block gbk %}
<meta charset="utf-8">
{% endblock %}
{% block ul %}
<ul id="starlist">
      <li><a href="/web/index/">网站首页</a></li>

      <li><a href="/web/list/">我的文章</a></li>
      <li ><a href="/web/about/">关于我</a></li>
      <li><a href="/web/login/">退出登录</a></li>
      <!--<li><a href="/back/index/">进入后台</a></li>-->
      <!--<li><a href="infopic.html">内容页</a></li>-->
    </ul>
{% endblock %}

{% block class %}
<article>
  <aside class="l_box">
      <div class="about_me">
        <h2>关于我</h2>
        <ul>
          <i><img src="/static/web/images/4.jpg"></i>
          <p><b>昊天</b>，一个90后草根菜鸟！10年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。</p>
        </ul>
      </div>
      <!--<div class="wdxc">-->
        <!--<h2>我的相册</h2>-->
        <!--<ul>-->
          <!--<li><a href="/"><img src="../../static/web/images/7.jpg"></a></li>-->
          <!--<li><a href="/"><img src="../../static/web/images/8.jpg"></a></li>-->
          <!--<li><a href="/"><img src="../../static/web/images/9.jpg"></a></li>-->
          <!--<li><a href="/"><img src="../../static/web/images/10.jpg"></a></li>-->
          <!--<li><a href="/"><img src="../../static/web/images/11.jpg"></a></li>-->
          <!--<li><a href="/"><img src="../../static/web/images/12.jpg"></a></li>-->
        <!--</ul>-->
      <!--</div>-->
      <div class="search">
        <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
          <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
          <input name="show" value="title" type="hidden">
          <input name="tempid" value="1" type="hidden">
          <input name="tbname" value="news" type="hidden">
          <input name="Submit" class="input_submit" value="搜索" type="submit">
        </form>
      </div>
      <div class="fenlei">
        <h2>文章分类</h2>
        <ul>
          <li><a href="http://www.runoob.com/">学无止境</a></li>
          <li><a href="/">日记</a></li>
          <li><a href="/">慢生活</a></li>
          <li><a href="/">美文欣赏</a></li>
        </ul>
      </div>
      <div class="tuijian">
        <!--<h2>站长推荐</h2>-->
        <!--<ul>-->
          <!--<li><a href="/">你是什么人便会遇上什么人</a></li>-->
          <!--<li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>-->
          <!--<li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>-->
          <!--<li><a href="/">个人博客模板《绅士》后台管理</a></li>-->
          <!--<li><a href="/">你是什么人便会遇上什么人</a></li>-->
          <!--<li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>-->
          <!--<li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>-->
          <!--<li><a href="/">个人博客模板《绅士》后台管理</a></li>-->
        <!--</ul>-->
      <!--</div>-->
      <div class="links">
        <h2>友情链接</h2>
        <ul>
          <a href="http://www.yangqq.com">昊天个人博客</a> <a href="http://www.yangqq.com">昊天博客</a>
        </ul>
      </div>
      <div class="guanzhu">
        <h2>关注我 么么哒</h2>
        <ul>
          <img src="../../static/web/images/wx.jpg">
        </ul>
      </div>
  </aside>
  <main class="r_box">
    {% for article in articles %}
    <li>
      <h3><a href="{{ url_for('web.web_info',id=article.id) }}">{{article.id}}</a></h3>
      <p>{{article.desc}}</p>
    </li>
    {% endfor %}
  </main>
</article>
<!--<footer>-->
  <!--<p>Design by <a href="http://www.yangqq.com" target="_blank">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>-->
<!--</footer>-->
<!--<a href="#" class="cd-top">Top</a>-->
{% endblock %}

templates/web/info.html
{% extends 'web/base.html' %}
{% block ul %}
<ul id="starlist">
      <li><a href="/web/index/" >网站首页</a></li>
      <!--<li><a href="share.html">我的相册</a></li>-->
      <li><a href="/web/list/">我的文章</a></li>
      <li ><a href="/web/about/" >关于我</a></li>
        <li><a href="/web/login/">退出登录</a></li>

      <!--<li><a href="gbook.html">留言</a></li>-->
      <!--<li><a href="/web/info/">内容页</a></li>-->
      <!--<li><a href="infopic.html">内容页</a></li>-->
    </ul>
{% endblock %}
{% block class %}
<article>
  <aside class="l_box">
    <div class="search">
      <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" type="submit">
      </form>
    </div>
    <div class="fenlei">
      <h2>文章分类</h2>
      <ul>
        <li><a href="/">学无止境（33）</a></li>
        <li><a href="/">日记（19）</a></li>
        <li><a href="/">慢生活（520）</a></li>
        <li><a href="/">美文欣赏（40）</a></li>
      </ul>
    </div>
    <!--<div class="tuijian">-->
      <!--<h2>站长推荐</h2>-->
      <!--<ul>-->
        <!--<li><a href="/">你是什么人便会遇上什么人</a></li>-->
        <!--<li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>-->
        <!--<li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>-->
        <!--<li><a href="/">个人博客模板《绅士》后台管理</a></li>-->
        <!--<li><a href="/">你是什么人便会遇上什么人</a></li>-->
        <!--<li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>-->
        <!--<li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>-->
        <!--<li><a href="/">个人博客模板《绅士》后台管理</a></li>-->
      <!--</ul>-->
    <!--</div>-->
    <!--<div class="tuijian">-->
      <!--<h2>点击排行</h2>-->
      <!--<ul>-->
        <!--<li><a href="/">你是什么人便会遇上什么人</a></li>-->
        <!--<li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>-->
        <!--<li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>-->
        <!--<li><a href="/">个人博客模板《绅士》后台管理</a></li>-->
        <!--<li><a href="/">你是什么人便会遇上什么人</a></li>-->
        <!--<li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>-->
        <!--<li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>-->
        <!--<li><a href="/">个人博客模板《绅士》后台管理</a></li>-->
      <!--</ul>-->
    <!--</div>-->
    <!--<div class="cloud">-->
      <!--<h2>标签云</h2>-->
      <!--<ul>-->
        <!--<a href="/">陌上花开</a> <a href="/">校园生活</a> <a href="/">html5</a> <a href="/">SumSung</a> <a href="/">青春</a> <a href="/">温暖</a> <a href="/">阳光</a> <a href="/">三星</a><a href="/">索尼</a> <a href="/">华维荣耀</a> <a href="/">三星</a> <a href="/">索尼</a>-->
      <!--</ul>-->
    <!--</div>-->
    <div class="guanzhu">
      <h2>关注我 么么哒</h2>
      <ul>
        <img src="images/wx.jpg">
      </ul>
    </div>
  </aside>
  <main>
    <div class="infosbox">
      <div class="newsview">
        <h3 class="news_title">{{ article.title }}</h3>
        <div class="bloginfo">
          <ul>
            <li class="author">作者：<a href="/">昊天</a></li>
            <li class="lmname"><a href="/">{{ article.tp.t_name }}</a></li>
            <li class="timer">{{ article.create_time }}</li>
            <!--<li class="view">4567人已阅读</li>-->
          </ul>
        </div>
        <div class="tags"><a href="/" target="_blank">个人博客</a> &nbsp; <a href="/" target="_blank">小世界</a></div>
        <div class="news_about">
        <div class="news_con">
          <br>{{ article.content |safe}}

          &nbsp; </div>
      </div>
      <!--<div class="share">-->
        <!--<p class="diggit"><a href="JavaScript:makeRequest('/e/public/digg/?classid=3&amp;id=19&amp;dotop=1&amp;doajax=1&amp;ajaxarea=diggnum','EchoReturnedText','GET','');"> 很赞哦！ </a>(<b id="diggnum"><script type="text/javascript" src="/e/public/ViewClick/?classid=2&id=20&down=5"></script>13</b>)</p>-->
      <!--</div>-->
      <div class="nextinfo">
        <p>上一篇：<a href="/news/life/2018-03-13/804.html">作为一个设计师,如果遭到质疑你是否能恪守自己的原则?</a></p>
        <p>下一篇：<a href="/news/life/">返回列表</a></p>
      </div>
      <div class="news_pl">
        <h2>文章评论</h2>
        <div class="gbko"> 
          <script src="/e/pl/more/?classid=77&amp;id=106&amp;num=20"></script>
          <div class="fb">
            <ul>
              <p class="fbtime"><span>2018-07-24 11:52:38</span>dancesmile</p>
              <p class="fbinfo">这才是我要的朋友圈</p>
            </ul>
          </div>
          <div class="fb">
            <ul>
              <p class="fbtime"><span>2018-07-24 08:52:48</span> 卜野</p>
              <p class="fbinfo"></p>
              <div class="ecomment"><span class="ecommentauthor">网友 家蚂蚁 的原文：</span>
                <p class="ecommenttext">坚持哟!看你每天都有写，请继续加油，再接再厉哦</p>
              </div>
            </ul>
          </div>
          
          <script>
		  function CheckPl(obj)
		  {
		  if(obj.saytext.value=="")
		  {
		  alert("您没什么话要说吗？");
		  obj.saytext.focus();
		  return false;
		  }
		  return true;
		  }
		  </script>
          <form action="/e/pl/doaction.php" method="post" name="saypl" id="saypl" onsubmit="return CheckPl(document.saypl)">
            <div id="plpost">
              <p class="saying"><span><a href="/e/pl/?classid=77&amp;id=106">共有<script type="text/javascript" src="/e/public/ViewClick/?classid=77&amp;id=106&amp;down=2"></script>2条评论</a></span>来说两句吧...</p>
              <p class="yname"><span>用户名:</span>
                <input name="username" type="text" class="inputText" id="username" value="" size="16">
              </p>
              <p class="yzm"><span>验证码:</span>
                <input name="key" type="text" class="inputText" size="16">
              </p>
              <input name="nomember" type="hidden" id="nomember" value="1" checked="checked">
              <textarea name="saytext" rows="6" id="saytext"></textarea>
              <input name="imageField" type="submit" value="提交">
              <input name="id" type="hidden" id="id" value="106">
              <input name="classid" type="hidden" id="classid" value="77">
              <input name="enews" type="hidden" id="enews" value="AddPl">
              <input name="repid" type="hidden" id="repid" value="0">
              <input type="hidden" name="ecmsfrom" value="/joke/talk/2018-07-23/106.html">
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
{% endblock %}

templates/web/list.html
{% extends 'web/base.html' %}
{% block ul %}
<ul id="starlist">
      <li><a href="/web/index/" >网站首页</a></li>
      <!--<li><a href="share.html">我的相册</a></li>-->
      <li><a href="/web/list/">我的文章</a></li>
      <li ><a href="/web/about/">关于我</a></li>
          <li><a href="/web/login/">退出登录</a></li>

      <!--<li><a href="gbook.html">留言</a></li>-->
      <!--<li><a href="/web/info/">内容页</a></li>-->
      <!--<li><a href="infopic.html">内容页</a></li>-->
    </ul>
{% endblock %}
{% block class %}
<article>
  <aside class="l_box">
 <div class="search">
      <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" type="submit">
      </form>
    </div>
    <div class="fenlei">
      <h2>文章分类</h2>
      <ul>
        <li><a href="/">学无止境</a></li>
        <li><a href="/">日记</a></li>
        <li><a href="/">慢生活</a></li>
        <li><a href="/">美文欣赏</a></li>
      </ul>
    </div>
    <!--<div class="tuijian">-->
      <!--<h2>站长推荐</h2>-->
      <!--<ul>-->
        <!--<li><a href="/">你是什么人便会遇上什么人</a></li>-->
        <!--<li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>-->
        <!--<li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>-->
        <!--<li><a href="/">个人博客模板《绅士》后台管理</a></li>-->
        <!--<li><a href="/">你是什么人便会遇上什么人</a></li>-->
        <!--<li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>-->
        <!--<li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>-->
        <!--<li><a href="/">个人博客模板《绅士》后台管理</a></li>-->
      <!--</ul>-->
    <!--</div>-->
     <div class="tuijian">
      <h2>点击排行</h2>
      <ul>
        <li><a href="/">你是什么人便会遇上什么人</a></li>
        <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
        <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
        <li><a href="/">个人博客模板《绅士》后台管理</a></li>
        <li><a href="/">你是什么人便会遇上什么人</a></li>
        <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
        <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
        <li><a href="/">个人博客模板《绅士》后台管理</a></li>
      </ul>
    </div>
<!--<div class="cloud">-->
      <!--<h2>标签云</h2>-->
      <!--<ul>-->
        <!--<a href="/">陌上花开</a> <a href="/">校园生活</a> <a href="/">html5</a> <a href="/">SumSung</a> <a href="/">青春</a> <a href="/">温暖</a> <a href="/">阳光</a> <a href="/">三星</a><a href="/">索尼</a> <a href="/">华维荣耀</a> <a href="/">三星</a> <a href="/">索尼</a>-->
      <!--</ul>-->
    <!--</div>-->
    <div class="guanzhu">
      <h2>关注我 么么哒</h2>
      <ul>
        <img src="/static/web/images/wx.jpg">
      </ul>
    </div>
  </aside>
  <main class="r_box">
      {% for article in articles %}
      <li>
          <th>文章标题</th>
      <h3><a href="{{ url_for('web.web_info',id=article.id) }}">{{ article.title }}</a></h3>
      <br>
       <th>文章内容</th>
          <hr/>
      <p>{{ article.content|safe }}</p>
      <br>
    </li>
      {% endfor %}
    <div class="pagelist"><a class="allpage"><b>99</b></a>&nbsp;&nbsp;<a href="#" class="curPage">1</a>&nbsp;&nbsp;<a href="#" onclick="page(2)">2</a>&nbsp;&nbsp;<a href="#" onclick="page(3)">3</a>&nbsp;&nbsp;<a href="#" onclick="page(4)">4</a>&nbsp;&nbsp;<a href="#" onclick="page(5)">5</a>&nbsp;&nbsp;<a href="#" onclick="page(6)">6</a>&nbsp;&nbsp;<a href="#" onclick="page(7)">7</a>&nbsp;&nbsp;<a href="#" onclick="page(8)">8</a>&nbsp;&nbsp;<a href="#" onclick="page(9)">9</a>&nbsp;&nbsp;<a href="#" onclick="page(2)">下一页</a></div>
  </main>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
{% endblock %}