back/models.py
from datetime import datetime

from flask_sqlalchemy import SQLAlchemy

db =SQLAlchemy()



class User(db.Model):
    id = db.Column(db.Integer,primary_key=True,autoincrement=True)
    username = db.Column(db.String(10),unique=True,nullable=False)
    password = db.Column(db.String(255),nullable=False)
    is_del=db.Column(db.Boolean,default=0)
    create_time =db.Column(db.DateTime,default=datetime.now)

    __tablename__="user"



class ArticleType(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    t_name =db.Column(db.String(10),unique=True,nullable=False)
    # a_name = db.Column(db.String(20),nullable=False)#分类名
    arts = db.relationship('Article',backref='tp')

    __tablename__ = "art_type"


class Article(db.Model):
    id = db.Column(db.Integer,primary_key=True,autoincrement=True)
    title=db.Column(db.String(30),unique=True,nullable=False)
    desc = db.Column(db.String(100),nullable=False)
    content = db.Column(db.Text,nullable=False)
    create_time =db.Column(db.DateTime,default=datetime.now)
    # len = db.Column(db.Integer,nullable=True)
    type = db.Column(db.Integer,db.ForeignKey('art_type.id'))







#保存
    def save(self):
        db.session.add(self)
        db.session.commit()

#删除
    def __delete__(self):
        db.session.delete(self)
        db.session.commit()

back/views.py
from flask import Blueprint, request, render_template, redirect, url_for, make_response, session

from werkzeug.security import generate_password_hash,check_password_hash
from back.models import db, User, ArticleType,Article
from utils.functions import is_login

back_blueprint = Blueprint('back',__name__)

@back_blueprint.route('/create_db/',methods=['GET'])
def create_db():
    db.create_all()
    return '创建表成功'

#文章分类
@back_blueprint.route('/category/',methods=['GET','POST'])
@is_login
def category():
    if request.method == 'GET':
        # types = ArticleType.query.order_by(ArticleType.id).all()
        types = ArticleType.query.all()
        return render_template('back/category.html',types=types)
    if request.method == 'POST':
        return redirect(url_for('back.add_type'))


#修改分类
@back_blueprint.route('/update_category/<int:id>',methods=['GET','POST'])
@is_login
def update_category(id):
    if request.method == 'GET':
        categorys=ArticleType.query.get(id)
        return render_template('back/update-category.html',categorys=categorys)
    if request.method == 'POST':
        ArticleType.id = request.view_args.get('id')
        type = ArticleType()
        if  type.id == request.view_args.get('id'):
            del_article_type(type.id)
        type.id=id
        type.t_name=request.values.get('t_name')
        db.session.add(type)
        db.session.commit()
        return redirect(url_for('back.category'))


#添加后的文章分类
@back_blueprint.route('/a_type/',methods=['GET','POST'])
def a_type():
    if request.method == 'GET':
        types=ArticleType.query.all()
        return render_template('back/category.html',types=types)


#添加文章分类
@back_blueprint.route('/add_type/',methods=["POST","GET"])
def add_type():
    if request.method == 'GET':
        return render_template('back/category_add.html')

    if request.method == 'POST':
        atype=request.form.get('atype')
        if atype:
            art_type =ArticleType()
            art_type.t_name=atype
            db.session.add(art_type)
            db.session.commit()
            return redirect(url_for('back.category'))
        else:
            error ='请填写分类信息'
            return render_template('back/category_add.html',error=error)


#删除文章
@back_blueprint.route('/del_article_type/<int:id>/',methods=['GET'])
def del_article_type(id):
    delart = ArticleType.query.get(id)
    db.session.delete(delart)
    db.session.commit()
    return redirect(url_for('back.category'))


#首页
@back_blueprint.route('/index/', methods=['GET'])
@is_login
def index():

    username=session.get('username')
    return render_template('back/index.html',username=username)

#退出登录
@back_blueprint.route('/logout/',methods=['GET'])
@is_login
def logout():
    del session['user_id']
    return redirect(url_for('back.login'))




#注册
@back_blueprint.route('/register/',methods=['GET','POST'])
def register():
    if request.method == 'GET':
        return render_template('back/register.html')

    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        password2 = request.form.get('password2')

        if username and password and password2:
            user = User.query.filter(User.username == username).first()
            if user:
                error = '该账号已注册，请更换账号'
                return render_template('back/register.html', error=error)
            else:
                if password2 == password:
                    user = User()
                    user.username = username
                    user.password = generate_password_hash(password)
                    db.session.add(user)
                    db.session.commit()
                    return redirect(url_for('back.login'))
                else:
                    error ='两次密码不一致'
                    return render_template('back/register.html',error=error)
        else:
                error = '请填写完整的信息'
                return render_template('back/register.html',error=error)


#登录
@back_blueprint.route('/login/',methods=["POST","GET"])
def login():
    if request.method == "GET":
        return render_template('back/login.html')
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        if username and password:
            user = User.query.filter(User.username == username).first()
            if not user:
                error = '该账号不存在，请去注册'
                return render_template('back/login.html',error=error)
            if not check_password_hash(user.password,password):
                error = '密码错误'
                return render_template('back/login.html',error=error)
            session['user_id'] = user.id
            return redirect(url_for('back.index'))
        else:
            error = '请填写完整的登录信息'
            return render_template('back/login.html', error=error)


#文章
@back_blueprint.route('/article/',methods=['GET','POST'])
@is_login
def article():
    if request.method == 'GET':
        articles =Article.query.all()
        return render_template('back/article.html',articles=articles)

# request.form_data_parser_class.parse_functions.__len__()
#添加文章
@back_blueprint.route('/add_article/',methods=['GET','POST'])
@is_login
def add_article():
    if request.method == 'GET':
       types = ArticleType.query.order_by(ArticleType.id).all()
       return render_template('back/add-article.html',types=types)
    if request.method == 'POST':
        title=request.form.get('title')
        desc=request.form.get('describe')
        content=request.form.get('content')
        type=request.form.get('category')
        art =Article()
        art.title=title
        art.desc=desc
        art.content=content
        art.type=type
        db.session.add(art)
        db.session.commit()
        return redirect(url_for('back.article'))


#修改文章
@back_blueprint.route('/update_article/<int:id>/',methods=['GET','POST'])
@is_login
def update_article(id):
    if request.method == 'GET':
        articles=Article.query.get(id)
        types = ArticleType.query.order_by(ArticleType.id).all()
        return render_template('back/update-article.html',articles=articles,types=types)
    if request.method == 'POST':

        Article.id = request.view_args.get('id')
        art = Article()
        if art.id==request.view_args.get('id'):
            del_article(id)
        art.id=id
        art.title = request.form['title']
        art.desc = request.form.get('describe')
        art.content = request.form.get('content')
        art.type = request.form.get('category')
        db.session.add(art)
        db.session.commit()
        return redirect(url_for('back.article'))


#删除文章
@back_blueprint.route('/del_article/<int:id>/',methods=['GET'])
def del_article(id):
    delart = Article.query.get(id)
    db.session.delete(delart)
    db.session.commit()
    return redirect(url_for('back.article'))



#用户管理
@back_blueprint.route('/manage-user/',methods=['GET'])
@is_login
def manage_user():
    return render_template('back/manage-user.html')


#登录管理
@back_blueprint.route('/loginlog/',methods=['GET'])
@is_login
def loginlog():
    return render_template('back/loginlog.html')

templates/back/add-article.html
{% extends 'back/base.html' %}
{% block css %}{{ super() }}{% endblock %}
{% block image %}{{ super() }}{% endblock %}
{% block js %}{{ super() }}{% endblock %}
{% block act %}
  <div class="row">
    <aside class="col-sm-3 col-md-2 col-lg-2 sidebar">
      <ul class="nav nav-sidebar">
        <li ><a href="/back/index/">报告</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li class="active"><a href="/back/article/">文章</a></li>
        <li><a href="#">公告</a></li>
        <li><a href="#">评论</a></li>
        <li><a data-toggle="tooltip" data-placement="top" title="网站暂无留言功能">留言</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="/back/category/">分类</a></li>
        <li ><a class="dropdown-toggle" id="otherMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">其他</a>
          <ul class="dropdown-menu" aria-labelledby="otherMenu">
            <li><a href="#">友情链接</a></li>
            <li><a href="/back/loginlog/">访问记录</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a class="dropdown-toggle" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">用户</a>
          <ul class="dropdown-menu" aria-labelledby="userMenu">
            <li><a href="#">管理用户组</a></li>
            <li><a href="/back/manage-user/">管理用户</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="/back/loginlog/">管理登录日志</a></li>
          </ul>
        </li>
        <li><a class="dropdown-toggle" id="settingMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">设置</a>
          <ul class="dropdown-menu" aria-labelledby="settingMenu">
            <li><a href="#">基本设置</a></li>
            <li><a href="#">用户设置</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">安全配置</a></li>
            <li role="separator" class="divider"></li>
            <li class="disabled"><a>扩展菜单</a></li>
          </ul>
        </li>
      </ul>
    </aside>
    {% endblock %}
{% block body %}{{ super() }}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <div class="row">
        <form action="" method="post" class="add-article-form">
          <div class="col-md-9">
            <h1 class="page-header">撰写新文章</h1>
            <div class="form-group">
              <label for="article-title" class="sr-only">标题</label>
              <input type="text" id="article-title" name="title" class="form-control" placeholder="在此处输入标题" value= ""
                     required autofocus autocomplete="off" >
            </div>
            <div class="form-group">
              <label for="article-content" class="sr-only">内容</label>

              <script id="article-content" name="content" type="text/plain" >{{content }}</script>

            </div>
            <div class="add-article-box">
              <h2 class="add-article-box-title"><span>关键字</span></h2>
              <div class="add-article-box-content">

              	<input type="text" class="form-control" placeholder="请输入关键字" name="keywords" autocomplete="off">

                <span class="prompt-text">多个标签请用英文逗号,隔开。</span>
              </div>
            </div>
            <div class="add-article-box">
              <h2 class="add-article-box-title"><span>描述</span></h2>
              <div class="add-article-box-content">

              	<textarea class="form-control" name="describe"    autocomplete="off">{{desc}}</textarea>

                <span class="prompt-text">描述是可选的手工创建的内容总结，并可以在网页描述中使用</span>
              </div>
            </div>
          </div>
          <div class="col-md-3">
            <h1 class="page-header">操作</h1>
            <div class="add-article-box">
              <h2 class="add-article-box-title"><span>分类</span></h2>
              <select id="'category-fname" class="form-control" name="category">
                {% for type in types %}
                <option value="{{ type.id }}">{{ type.t_name }}</option>
                {% endfor %}
              </select>
              <!--<div class="add-article-box-content">-->

                <!--<ul class="category-list">-->

                  <!--<li>-->
                    <!--&lt;!&ndash;{{type}}&ndash;&gt;-->
                    <!--<label>-->
                      <!--<input name="type" type="radio" value="1" checked>-->
                       <!--html<em class="hidden-md">( 分类ID: <span>1</span> )</em></label>-->
                  <!--</li>-->

                  <!--<li>-->
                    <!--<label>-->
                      <!--<input name="type" type="radio" value="2">-->
                       <!--python<em class="hidden-md">( 分类ID: <span>2</span> )</em></label>-->
                  <!--</li>-->
                  <!--<li>-->
                    <!--<label>-->
                      <!--<input name="type" type="radio" value="3">-->
                      <!--web <em class="hidden-md">( 分类ID: <span>3</span> )</em></label>-->
                  <!--</li>-->
                  <!--<li>-->
                    <!--<label>-->
                      <!--<input name="type" type="radio" value="4">-->
                      <!--java <em class="hidden-md">( 分类ID: <span>4</span> )</em></label>-->
                  <!--</li>-->
                  <!--<li>-->
                    <!--<label>-->
                      <!--<input name="type" type="radio" value="5">-->
                       <!--<em class="hidden-md">( 分类ID: <span>5</span> )</em></label>-->
                  <!--</li>-->
                </ul>
              </div>
            </div>

              <div class="add-article-box-footer">
                <button class="btn btn-default" type="button" ID="upImage">图片选择</button>
              </div>
            </div>
            <div class="add-article-box">
              <h2 class="add-article-box-title"><span>发布</span></h2>
              <div class="add-article-box-content">
              	<p><label>状态：</label><span class="article-status-display">未发布</span></p>
                <p><label>公开度：</label><input type="radio" name="visibility" value="0" checked/>公开 <input type="radio" name="visibility" value="1" />加密</p>
                <p><label>发布于：</label><span class="article-time-display">{{create_time}}<input style="border: none;" type="datetime" name="time" /></span></p>
              </div>
              <div class="add-article-box-footer">
                <button class="btn btn-primary" type="submit" name="submit">发布</button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>

<script src="/static/back/lib/ueditor/ueditor.config.js"></script>
<script src="/static/back/lib/ueditor/ueditor.all.min.js"> </script>
<script src="/static/back/lib/ueditor/lang/zh-cn/zh-cn.js"></script>
<script id="uploadEditor" type="text/plain" style="display:none;"></script>
<script type="text/javascript">
var editor = UE.getEditor('article-content');
window.onresize=function(){
    window.location.reload();
}
var _uploadEditor;
$(function () {
    //重新实例化一个编辑器，防止在上面的editor编辑器中显示上传的图片或者文件
    _uploadEditor = UE.getEditor('uploadEditor');
    _uploadEditor.ready(function () {
        //设置编辑器不可用
        //_uploadEditor.setDisabled();
        //隐藏编辑器，因为不会用到这个编辑器实例，所以要隐藏
        _uploadEditor.hide();
        //侦听图片上传
        _uploadEditor.addListener('beforeInsertImage', function (t, arg) {
            //将地址赋值给相应的input,只去第一张图片的路径
            $("#pictureUpload").attr("value", arg[0].src);
            //图片预览
            //$("#imgPreview").attr("src", arg[0].src);
        })
        //侦听文件上传，取上传文件列表中第一个上传的文件的路径
        _uploadEditor.addListener('afterUpfile', function (t, arg) {
            $("#fileUpload").attr("value", _uploadEditor.options.filePath + arg[0].url);
        })
    });
});
//弹出图片上传的对话框
$('#upImage').click(function () {
    var myImage = _uploadEditor.getDialog("insertimage");
    myImage.open();
});
//弹出文件上传的对话框
function upFiles() {
    var myFiles = _uploadEditor.getDialog("attachment");
    myFiles.open();
}
</script>
{% endblock %}

templates/back/article.html
{% extends 'back/base.html' %}

{% block act %}
  <div class="row">
    <aside class="col-sm-3 col-md-2 col-lg-2 sidebar">
      <ul class="nav nav-sidebar">
        <li ><a href="/back/index/">报告</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li class="active"><a href="/back/article/">文章</a></li>
        <li><a href="#">公告</a></li>
        <li><a href="#">评论</a></li>
        <li><a data-toggle="tooltip" data-placement="top" title="网站暂无留言功能">留言</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="/back/category/">分类</a></li>
        <li ><a class="dropdown-toggle" id="otherMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">其他</a>
          <ul class="dropdown-menu" aria-labelledby="otherMenu">
            <li><a href="#">友情链接</a></li>
            <li><a href="/back/loginlog/">访问记录</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a class="dropdown-toggle" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">用户</a>
          <ul class="dropdown-menu" aria-labelledby="userMenu">
            <li><a href="#">管理用户组</a></li>
            <li><a href="/back/manage-user/">管理用户</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="/back/loginlog/">管理登录日志</a></li>
          </ul>
        </li>
        <li><a class="dropdown-toggle" id="settingMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">设置</a>
          <ul class="dropdown-menu" aria-labelledby="settingMenu">
            <li><a href="#">基本设置</a></li>
            <li><a href="#">用户设置</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">安全配置</a></li>
            <li role="separator" class="divider"></li>
            <li class="disabled"><a>扩展菜单</a></li>
          </ul>
        </li>
      </ul>
    </aside>
    {% endblock %}
{% block body %}{{ super() }}

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <form action="" method="post" >
        <h1 class="page-header">操作</h1>
        <ol class="breadcrumb">
          <li><a href="/back/add_article/">增加文章</a></li>
        </ol>
        <h1 class="page-header">管理 <span class="badge"></span></h1>
        <div class="table-responsive">

          <table class="table table-striped table-hover">

            <thead>
              <tr>
                <th><span class="glyphicon glyphicon-th-large"></span> <span class="visible-lg">标题</span></th>

                <!--<th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">内容</span></th>-->
                <!--<th><span class="glyphicon glyphicon-list"></span> <span class="visible-lg">描述</span></th>-->
                <th class="hidden-sm"><span class="glyphicon glyphicon-tag"></span> <span class="visible-lg">分类id</span></th>
                <!--<th class="hidden-sm"><span class="glyphicon glyphicon-comment"></span> <span class="visible-lg">ID</span></th>-->
                <th><span class="glyphicon glyphicon-time"></span> <span class="visible-lg">创建日期</span></th>
                <th><span class="glyphicon glyphicon-pencil"></span> <span class="visible-lg">操作</span></th>
              </tr>
            </thead>
             {% for article in articles %}

            <tbody>

              <tr>
                <td class="article-title">{{ article.title }}</td>
                <!--<td><input type="checkbox" class="input-control" name="checkbox[]"  />{{article.content|safe}}</td>-->
                <!--<td>{{ article.desc }}</td>-->

                <td class="hidden-sm">{{article.tp.t_name}}</td>

                <!--<td class="hidden-sm">id{{articles.id}}</td>-->
                <td>{{article.create_time}}</td>
                <td><a href="{{ url_for('back.update_article',id=article.id )}}">修改</a> /
                <a rel="6" href="{{ url_for('back.del_article',id=article.id )}}">删除</a></td>
              </tr>

            </tbody>
            {% endfor %}
          </table>
        </div>

        <!--<footer class="message_footer">-->
          <!--<nav>-->
            <!--<div class="btn-toolbar operation" role="toolbar">-->
              <!--<div class="btn-group" role="group"> <a class="btn btn-default" onClick="select()">全选</a> <a class="btn btn-default" onClick="reverse()">反选</a> <a class="btn btn-default" onClick="noselect()">不选</a> </div>-->
              <!--<div class="btn-group" role="group">-->
                <!--<button type="submit" class="btn btn-default" data-toggle="tooltip" data-placement="bottom" title="删除全部选中" name="checkbox_delete">删除</button>-->
              <!--</div>-->
            <!--</div>-->
            <ul class="pagination pagenav">
              <li class="disabled"><a aria-label="Previous"> <span aria-hidden="true">&laquo;</span> </a> </li>
              <li class="active"><a href="#">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li><a href="#">5</a></li>
              <li><a href="#" aria-label="Next"> <span aria-hidden="true">&raquo;</span> </a> </li>
            </ul>
          </nav>
        </footer>
      </form>
    </div>

{% endblock %}

templates/back/category.html
{% extends 'back/base.html' %}
 {% block title %}
文章分类
  {% endblock %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='back/css/bootstrap.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='back/css/style.css')}}">
<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='back/css/font-awesome.min.css')}}">
{% endblock %}
{% block image %}{{ super() }}{% endblock %}
{% block js %}{{ super() }}{% endblock %}
{% block act %}
  <div class="row">
    <aside class="col-sm-3 col-md-2 col-lg-2 sidebar">
      <ul class="nav nav-sidebar">
        <li ><a href="/back/index/">报告</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li ><a href="/back/article/">文章</a></li>
        <li><a href="#">公告</a></li>
        <li><a href="#">评论</a></li>
        <li><a data-toggle="tooltip" data-placement="top" title="网站暂无留言功能">留言</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li class="active"><a href="/back/category/">分类</a></li>
        <li ><a class="dropdown-toggle" id="otherMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">其他</a>
          <ul class="dropdown-menu" aria-labelledby="otherMenu">
            <li><a href="#">友情链接</a></li>
            <li><a href="/back/loginlog/">访问记录</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a class="dropdown-toggle" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">用户</a>
          <ul class="dropdown-menu" aria-labelledby="userMenu">
            <li><a href="#">管理用户组</a></li>
            <li><a href="/back/manage-user/">管理用户</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="/back/loginlog/">管理登录日志</a></li>
          </ul>
        </li>
        <li><a class="dropdown-toggle" id="settingMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">设置</a>
          <ul class="dropdown-menu" aria-labelledby="settingMenu">
            <li><a href="#">基本设置</a></li>
            <li><a href="#">用户设置</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">安全配置</a></li>
            <li role="separator" class="divider"></li>
            <li class="disabled"><a>扩展菜单</a></li>
          </ul>
        </li>
      </ul>
    </aside>
    {% endblock %}
{% block body %}{{ super() }}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <div class="row">
        <div class="col-md-5">
          <h1 class="page-header">添加</h1>
          <form action="" method="post" autocomplete="off">
            <button class="btn btn-primary" type="submit" name="submit">添加分类名</button>
          </form>
        </div>
        <div class="col-md-7">
          <h1 class="page-header">分类管理 <span class="badge"></span></h1>
          <div class="table-responsive">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th><span class="glyphicon glyphicon-paperclip"></span> <span class="visible-lg">ID</span></th>
                  <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">名称</span></th>
                  <th><span class="glyphicon glyphicon-pencil"></span> <span class="visible-lg">操作</span></th>
                </tr>
              </thead>
              <tbody>
              {% for type in types %}
                <tr>
                  <td>{{ type.id }}</td>
                  <td>{{ type.t_name }}</td>
                  <td><a href="{{ url_for('back.update_category',id=type.id )}}">修改</a>
                    <a rel="1" href="{{ url_for('back.del_article_type',id=type.id )}}">删除</a></td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
            <span class="prompt-text"><strong>注：</strong>删除一个分类也会删除分类下的文章和子分类,请谨慎删除!</span> </div>
        </div>
      </div>
    </div>
  </div>



<script>

</script>
  {% endblock %}

templates/back/category_add.html
{% extends 'back/base.html' %}
{% block act %}
  <div class="row">
    <aside class="col-sm-3 col-md-2 col-lg-2 sidebar">
      <ul class="nav nav-sidebar">
        <li ><a href="/back/index/">报告</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li ><a href="/back/article/">文章</a></li>
        <li><a href="#">公告</a></li>
        <li><a href="#">评论</a></li>
        <li><a data-toggle="tooltip" data-placement="top" title="网站暂无留言功能">留言</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li class="active"><a href="/back/category/">分类</a></li>
        <li ><a class="dropdown-toggle" id="otherMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">其他</a>
          <ul class="dropdown-menu" aria-labelledby="otherMenu">
            <li><a href="#">友情链接</a></li>
            <li><a href="/back/loginlog/">访问记录</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav nav-sidebar">
        <li ><a class="dropdown-toggle" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">用户</a>
          <ul class="dropdown-menu" aria-labelledby="userMenu">
            <li><a href="#">管理用户组</a></li>
            <li><a href="/back/manage-user/">管理用户</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="/back/loginlog/">管理登录日志</a></li>
          </ul>
        </li>
        <li><a class="dropdown-toggle" id="settingMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">设置</a>
          <ul class="dropdown-menu" aria-labelledby="settingMenu">
            <li><a href="#">基本设置</a></li>
            <li><a href="#">用户设置</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">安全配置</a></li>
            <li role="separator" class="divider"></li>
            <li class="disabled"><a>扩展菜单</a></li>
          </ul>
        </li>
      </ul>
    </aside>
    {% endblock %}
{% block body %}{{ super() }}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <h1 class="page-header">添加文章分类</h1>
      <form action="" method="post">
        <div class="form-group">
          <label for="category-name">分类名称</label>

          <input type="text" id="category-name" name="atype" value="" class="form-control" placeholder="在此处输入分类名称"  required autocomplete="off">

          <button class="btn btn-primary" type="submit" name="submit">添加</button>
        </div>
      </form>
    </div>
{% endblock %}